---
- name: Configure EC2 instance
  remote_user: ec2-user
  become: yes
  become_method: sudo
  hosts: all
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes
